const OPENWEATHER_API_KEY = "21267ec3822e82b0ce0473bb0bfbe318";
final List<String> topCities = [
  'Tokyo',
  'Delhi',
  'Shanghai',
  'São Paulo',
  'Mexico City',
  'Cairo',
  'Mumbai',
  'Beijing',
  'Dhaka',
  'Osaka',
  'New York City',
  'Karachi',
  'Buenos Aires',
  'Istanbul',
  'Kolkata',
  'Manila',
  'Lagos',
  'Rio de Janeiro',
  'Kinshasa',
  'Guangzhou',
  'Los Angeles',
  'Moscow',
  'Lahore',
  'Bangalore',
  'Paris',
  'Bogotá',
  'Jakarta',
  'Chennai',
  'Lima',
  'Bangkok',
  'Seoul',
  'Nagoya',
  'Hyderabad',
  'London',
  'Tehran',
  'Chicago',
  'Chengdu',
  'Nanjing',
  'Wuhan',
  'Ho Chi Minh City',
  'Luanda',
  'Ahmedabad',
  'Kuala Lumpur',
  'Hong Kong',
  'Hangzhou',
  'Khartoum',
  'Madrid',
  'Pune',
  'Dallas',
  'Toronto',
  'Miami',
  'Riyadh',
  'Singapore',
  'Shenzhen',
  'Doha',
  'Baghdad',
  'Santiago',
  'Houston',
  'Boston',
  'Sydney',
  'Atlanta',
  'Frankfurt',
  'Milan',
  'Dubai',
  'Seattle',
  'Philadelphia',
  'Johannesburg',
  'Copenhagen',
  'Melbourne',
  'San Francisco',
  'Berlin',
  'Tel Aviv',
  'Amaravati',
  // Add more cities here if needed
];
